spring.application.name=dio-budgeting-gemini

spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash
app.gemini.tts.model=gemini-3.8-flash-lite-tts
app.gemini.tts.voice=Kore


logging.level.org.springframework.ai=DEBUG