spring.application.name=dio-budgeting-gemini

spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash
app.gemini.tts.model=gemini-3.8-flash-lite-tts
app.gemini.tts.voice=Kore
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=11MB

logging.level.org.springframework.ai=DEBUG
