spring.application.name=dio-budgeting-gemini

spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash

spring.ai.model.audio.transcription=openai
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.openai.audio.transcription.model=whisper-1
spring.ai.openai.audio.transcription.language=pt
spring.ai.openai.audio.transcription.response-format=text
spring.ai.openai.audio.transcription.prompt=Áudio em português brasileiro com descrição de gastos financeiros. As frases geralmente contêm um valor em reais, uma ação e um local ou estabelecimento.

logging.level.org.springframework.ai=DEBUG